### ISSUE TITLE
Episodes not showing up

### ISSUE THREAD

**Issue by cco3** [Podcastindex-org/web-ui#88]
This is almost certainly not the right repo to file an issue in / channel of communication, so I would appreciate help finding the right one.

Regardless, I'm trying to figure out why no episodes are appearing for the following podcast:
https://podcastindex.org/podcast/4096769

At first I assumed it was just because there is some service that needs to download the audio files first, but it's been 48 hours, so now I'm thinking there may be something wrong with the feed.  How do I go about debugging this?

**Comment by stevencrader** [comment]
I'm not sure either. I triggered a re-parse and no episodes are found. 

The feed doesn't seem to have any issues though. It passes validation at https://castfeedvalidator.com/?url=https://thedoreanprinciple.org/audiobook.rss

@daveajones

**Comment by daveajones** [comment]
Looking now.

**Comment by daveajones** [comment]
Your timestamps are wrong in the feed items.  They are all from September.  So, the index won't show those episodes until then.  See screenshot.
![image](https://user-images.githubusercontent.com/1498236/126520581-f7f67b42-84a8-469b-9b29-0fdbdb7227b7.png)

**Comment by daveajones** [comment]
When you correct that, let me know and I'll re-index the feed.

**Comment by cco3** [comment]
Ah...that was intentional because that's when I intend to publicize it...(that's when the book gets released).  Does it have to be manually reindexed or can I just update them and expect it to be fixed in a few days?

From a product perspective, would it make since to just display them with future dates?  This is how other podcast directories seem to work.

**Comment by cco3** [comment]
OK, I've updated the dates to be in the past.  Thanks for your help.

**Comment by daveajones** [comment]
That’s an interesting situation. I have always considered future dated episodes sort of like future dated blog posts - that they ar me meant to be revealed once the date passes. Will give this some thought.

**Comment by cco3** [comment]
Yeah, I guess I don't have a certain answer for this; just an observation of what other directories have done.  I guess one other point is that a public feed is public, so that would seem to argue that it shouldn't be hidden.

Still curious about how frequently podcastindex gets updated though.  I didn't see any documentation on that.

**Comment by stevencrader** [comment]
I've pinged the endpoint to force an update a couple of times and nothing has changed. Dave will need to look more since episodes are still not showing up.

**Comment by daveajones** [comment]
I’ll check it Steven. This is a good experiment of how the index handles this issue. 😊

**Comment by cco3** [comment]
Any new developments here?

**Comment by stevencrader** [comment]
@daveajones Is the date not a field that gets reparsed? These items are still not showing up.

**Comment by daveajones** [comment]
I thought I already fixed this. I’ll check in the morning.

**Comment by cco3** [comment]
I tried changing the paths of the mp3 files, but that didn't seem to help.  I'm guessing you all are keyed on the `guid`.

**Comment by stevencrader** [comment]
I see the Foreword is showing up but the rest are still not showing up. I triggered it to be reparsed but don't see any changes.

Unfortunately, @daveajones is the only one with access to the backend data.

**Comment by cco3** [comment]
Yes, that was a new entry I added...the others that used to have the date set to Sept 30 still don't show (though I'm guessing they may show come Sept 30).  In general, I'd like to be able to update this kind of metadata though.

**Comment by cco3** [comment]
This is a shot in the dark since I haven't done any real testing, but it looks like you are updating almost all the fields but the timestamp:
https://github.com/Podcastindex-org/aggregator/pull/15

**Comment by daveajones** [comment]
Fixed:  https://podcastindex.org/podcast/4096769

This is a feed change detection issue that I'm working through now.

**Comment by cco3** [comment]
Thanks!
